PUNCTUATION_MAP = {
    # German - Common, Mishearings
    'punkt': '.',
    'komma': ',',
    'fragezeichen': '?',
    'ausrufezeichen': '!',
    'doppelpunkt': ':',
    'semikolon': ';',
    'strichpunkt': ';',
    'klammer auf': '(',
    'klammer zu': ')',
    'runde klammer auf': '(',
    'runde klammer zu': ')',
    'eckige klammer auf': '[',
    'eckige klammer zu': ']',
    'geschweifte klammer auf': '{',
    'geschweifte klammer zu': '}',
    'bindestrich': '-',
    'minus': '-',
    'gedankenstrich': '–',
    'apostroph': "'",
    'hochkomma': "'",
    'anführungszeichen': '"',
    'anführungsstriche': '"',
    'schlusszeichen': '"',
    'gaensefuesschen': '"',
    'schrägstrich': '/',
    'slash': '/',
    'backslash': '\\',
    'unterstrich': '_',
    'punktpunktpunkt': '...',
    'raute': '#',
    'undzeichen': '&',
    'etzeichen': '&',
    'atzeichen': '@',
    'stern': '*',



    # English - Common, Mishearings
    'period': '.',
    'full stop': '.',
    'dot': '.',
    'point': '.',
    'comma': ',',
    'question mark': '?',
    'question MK': '?',
    'exclamation mark': '!',
    'exclamation point': '!',
    'colon': ':',
    'semicolon': ';',
    'parenthesis': '(',
    'parentheses': ('(', ')'),
    'open parenthesis': '(',
    'close parenthesis': ')',
    'bracket': '[',
    'open bracket': '[',
    'close bracket': ']',
    'brace': '{',
    'open brace': '{',
    'close brace': '}',
    'hyphen': '-',
    'dash': '-',
    'minus': '-',
    'apostrophe': "'",
    'quote': '"',
    'quotation mark': '"',
    'single quote': "'",
    'double quote': '"',
    'slash': '/',
    'backslash': '\\',
    'underscore': '_',
    'ellipsis': '...',
    'dot dot dot': '...',
    'hash': '#',
    'number sign': '#',
    'and sign': '&',
    'ampersand': '&',
    'at sign': '@',
    'star': '*',

    # GitHub

    'from get up': 'from GitHub',
    'get up': 'GitHub',

    'keep it up': 'GitHub',
    'good job': 'GitHub',
    'q-tip': 'GitHub',
    'kit': 'Git',

    'koffee pace': 'Copy Paste',
    'copy pace': 'Copy Paste',
    'hobby pest': 'Copy Paste',

    # lokale Berühmtheiten ;)
    'sebastian laufer': 'Sebastian Lauffer',
    'laufer': 'Lauffer',
    'harald utz': 'Harald Uetz',
    'harald öz': 'Harald Uetz',
    'uz': 'Uetz',
}
