# config/maps/plugins/0ad/de-DE/FUZZY_MAP_pre.py
import re # noqa: F401
# Auto-generated 0 A.D. Hotkeys

place = "(baue|errichte|platziere|build|place|bau|paul)"
select = "(select|auswählen|markieren|fokus|fokussiert|focus|fokussiere)"

FUZZY_MAP_pre = [
    ('K', fr"^{place}\s*(k|nowoundedonly)\w*$"),
    ('A', fr"^{place}\s*(arsenal|a)\w*$"),
    ('B', fr"^{place}\s*(barracks|b|kaserne)\w*$"),
    ('C', fr"^{place}\s*(zivil_zentrum|c|civil_centre)\w*$"),
    ('K', fr"^{place}\s*(k|corral|korral)\w*$"),
    ('D', fr"^{place}\s*(defense_tower|verteidigungsturm|d)\w*$"),
    ('E', fr"^{place}\s*(e|elephant_stables)\w*$"),
    ('F', fr"^{place}\s*(f|feld|field)\w*$"),
    ('N', fr"^{place}\s*(n|forge|schmiede)\w*$"),
    ('h', fr"^{place}\s*(\w+aus|bauhaus|h|haus|house|\w*aus)\w*$"),
    ('M', fr"^{place}\s*(markt|m|market)\w*$"),
    ('V', fr"^{place}\s*(v|stable|stabil)\w*$"),
    ('S', fr"^{place}\s*(s|lagerhaus|storehouse)\w*$"),
    ('T', fr"^{place}\s*(t|temple|tempel)\w*$"),
    ('U', fr"^{place}\s*(wallset_siege|u)\w*$"),
    ('W', fr"^{place}\s*(wallset_stone|w)\w*$"),
    ('Ctrl+A', fr"^{select}?\s*(ctrl+a|arsenal)\w*$"),
    ('Ctrl+A', fr"^{select}?\s*(ctrl+a|armycamp|armeelager)\w*$"),
    ('Ctrl+A', fr"^{select}?\s*(ctrl+a|assembly|montage)\w*$"),
    ('Ctrl+A', fr"^{select}?\s*(amphitheaterpompeii|amphitheater pompeji|ctrl+a)\w*$"),
    ('Ctrl+A', fr"^{select}?\s*(ctrl+a|zuschreibung|apadana)\w*$"),
    ('Ctrl+A', fr"^{select}?\s*(ctrl+a|arch|bogen)\w*$"),
    ('Ctrl+X', fr"^{select}?\s*(barracks|ctrl+x|kaserne)\w*$"),
    ('Ctrl+X', fr"^{select}?\s*(ctrl+x|elephantstable|elefantenstall)\w*$"),
    ('Ctrl+X', fr"^{select}?\s*(ctrl+x|stable|stabil)\w*$"),
    ('Ctrl+X', fr"^{select}?\s*(festung|ctrl+x|fortress)\w*$"),
    ('Ctrl+X', fr"^{select}?\s*(militärkolonie|ctrl+x|militarycolony)\w*$"),
    ('Ctrl+X', fr"^{select}?\s*(ctrl+x|arsenal)\w*$"),
    ('Ctrl+X', fr"^{select}?\s*(ctrl+x|armycamp|armeelager)\w*$"),
    ('Alt+K', fr"^{select}?\s*(catapult|katapult|alt+k)\w*$"),
    ('Ctrl+C', fr"^{select}?\s*(zentrum|cc|ctrl+c|zivilzentrum|dorfzentrum|civilcentre)\w*$"),
    ('Ctrl+C', fr"^{select}?\s*(ctrl+c|corral|korral)\w*$"),
    ('Ctrl+C', fr"^{select}?\s*(ritze|ctrl+c|crannog)\w*$"),
    ('Ctrl+F', fr"^{select}?\s*(ctrl+f|farmstead|bauernhof)\w*$"),
    ('Ctrl+F', fr"^{select}?\s*(ctrl+f|forge|schmiede)\w*$"),
    ('Ctrl+F', fr"^{select}?\s*(festung|ctrl+f|fortress)\w*$"),
    ('Ctrl+L', fr"^{select}?\s*(library|ctrl+l|bibliothek)\w*$"),
    ('Ctrl+M', fr"^{select}?\s*(markt|market|ctrl+m)\w*$"),
    ('Ctrl+M', fr"^{select}?\s*(militärkolonie|ctrl+m|militarycolony)\w*$"),
    ('Ctrl+S', fr"^{select}?\s*(ctrl+s|lagerhaus|storehouse)\w*$"),
    ('Ctrl+S', fr"^{select}?\s*(ctrl+s|ship|schiff)\w*$"),
    ('Ctrl+S', fr"^{select}?\s*(ctrl+s|stable|stabil)\w*$"),
    ('Ctrl+S', fr"^{select}?\s*(ctrl+s|elephantstable|elefantenstall)\w*$"),
    ('Ctrl+S', fr"^{select}?\s*(ctrl+s|farmstead|bauernhof)\w*$"),
    ('Ctrl+S', fr"^{select}?\s*(ctrl+s|forge|schmiede)\w*$"),
    ('Ctrl+S', fr"^{select}?\s*(ctrl+s|dock)\w*$"),
    ('Alt+C', fr"^{select}?\s*(alt+c|kavallerie|cavalry)\w*$"),
    ('Alt+H', fr"^{select}?\s*(healer|heiler|alt+h)\w*$"),
    ('Alt+I', fr"^{select}?\s*(infanterie|alt+i|infantry)\w*$"),
    ('Alt+V', fr"^{select}?\s*(alt+v|minister)\w*$"),
    ('J', fr"^{place}\s*(j|kavallerie|cavalry)\w*$"),
    ('J', fr"^{place}\s*(infanterie|j|infantry)\w*$"),
    ('J', fr"^{place}\s*(soldat|soldier|j)\w*$"),
    ('J', fr"^{place}\s*(siege|belagerung|j)\w*$"),
    ('J', fr"^{place}\s*(hund|dog|j)\w*$"),
    ('J', fr"^{place}\s*(elephant|j|elefant)\w*$"),
    ('J', fr"^{place}\s*(unterstützung|j|support)\w*$"),
    ('Ctrl+A', fr"^{select}?\s*(ctrl+a|arsenal)\w*$"),
    ('Ctrl+B', fr"^{select}?\s*(barracks|ctrl+b|kaserne)\w*$"),
    ('Ctrl+C', fr"^{select}?\s*(zivil_zentrum|ctrl+c|civil_centre)\w*$"),
    ('Ctrl+K', fr"^{select}?\s*(ctrl+k|corral|korral)\w*$"),
    ('Ctrl+D', fr"^{select}?\s*(defense_tower|verteidigungsturm|ctrl+d)\w*$"),
    ('Ctrl+J', fr"^{select}?\s*(ctrl+j|dock)\w*$"),
    ('Ctrl+E', fr"^{select}?\s*(ctrl+e|elephant_stables)\w*$"),
    ('Ctrl+G', fr"^{select}?\s*(ctrl+g|farmstead|bauernhof)\w*$"),
    ('Ctrl+Shift+F', fr"^{select}?\s*(ctrl+shift+f|feld|field)\w*$"),
    ('Ctrl+N', fr"^{select}?\s*(forge|schmiede|ctrl+n)\w*$"),
    ('Ctrl+R', fr"^{select}?\s*(festung|ctrl+r|fortress)\w*$"),
    ('Ctrl+H', fr"^{select}?\s*(ctrl+h|b\w+aus|bauhaus|haus|house|\w?aus)\w*$"),
    ('Ctrl+M', fr"^{select}?\s*(markt|market|ctrl+m)\w*$"),
    ('Ctrl+O', fr"^{select}?\s*(ctrl+o|outpost|vorposten)\w*$"),
    ('Ctrl+Y', fr"^{select}?\s*(ctrl+y|sentry_tower)\w*$"),
    ('Ctrl+Z', fr"^{select}?\s*(ctrl+z|stable|stabil)\w*$"),
    ('Ctrl+V', fr"^{select}?\s*(lagerhaus|ctrl+v|storehouse)\w*$"),
    ('Ctrl+T', fr"^{select}?\s*(temple|ctrl+t|tempel)\w*$"),
    ('Ctrl+W', fr"^{select}?\s*(wunder|wonder|ctrl+w)\w*$"),
    ('farmstead', fr"^{place}\s*(ortsfundament|placefoundation|farmstead)\w*$"),
    ('FemaleCitizen', fr"^{place}\s*(femalecitizen|einheiten auswählen|selectunits)\w*$"),
]
