# config/maps/plugins/internals/en-US/PUNCTUATION_MAP.py
# EXAMPLE: test
PUNCTUATION_MAP = {
    # Lowercase
    'zero': '0', 'one': '1', 'two': '2', 'three': '3',
    'five': '5', 'six': '6', 'seven': '7', 'eight': '8', 'nine': '9',
    'ten': '10', 'eleven': '11', 'twelve': '12', 'thirteen': '13',
    'fourteen': '14', 'fifteen': '15', 'sixteen': '16', 'seventeen': '17',
    'twenty': '20', 'thirty': '30', 'forty': '40', 'fifty': '50',
    'sixty': '60', 'seventy': '70', 'eighty': '80', 'ninety': '90',
    'hundred': '100', 'thousand': '1000',

    'period': '.',
    'full stop': '.',
    'torch': '.',
    'dot': '.',
    'point': '.',
    'comma': ',',
    'question mark': '?',
    'christian monk': '?',
    'christian luck': '?',
    'christian mk': '?',
    'question mk': '?',
    'exclamation mark': '!',
    'exclamation point': '!',
    'colon': ':',
    'semicolon': ';',
    'parenthesis': '(',
    'parentheses': ('(', ')'),
    'open parenthesis': '(',
    'close parenthesis': ')',
    'bracket': '[',
    'open bracket': '[',
    'close bracket': ']',
    'brace': '{',
    'open brace': '{',
    'close brace': '}',
    'hyphen': '-',
    'dash': '-',
    'minus': '-',
    'apostrophe': "'",
    'quote': '"',
    'quotation mark': '"',
    'single quote': "'",
    'double quote': '"',
    'slash': '/',
    'backslash': '\\',
    'underscore': '_',
    'ellipsis': '...',
    'dot dot dot': '...',
    'hash': '#',
    'number sign': '#',
    'and sign': '&',
    'ampersand': '&',
    'at sign': '@',
    'star': '*',


}
