#!/usr/bin/env python3
# generate_docs_index.py

import os
import logging
import sys
from pathlib import Path

project_root = Path(__file__).resolve().parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from scripts.py.func.get_project_root import get_aura_project_root

PROJECT_ROOT = get_aura_project_root()

# Basic logging setup
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# --- Configuration ---
DOCS_DIR = Path(__file__).parent
OUTPUT_FILENAME = "index.rst"
OUTPUT_FILEPATH = DOCS_DIR / OUTPUT_FILENAME
EXCLUDE_FILES = [OUTPUT_FILENAME]

def generate_docs_index():
    """
    Scans the DOCS_DIR for .rst files and generates a master index.rst file
    with a toctree directive to include them all in the Sphinx build.
    """
    logging.info(f"Starting to generate index for '{DOCS_DIR}' directory.")

    if not os.path.isdir(DOCS_DIR):
        logging.error(f"Directory not found: '{DOCS_DIR}'. Aborting.")
        return

    try:
        import shutil
        root_readme = PROJECT_ROOT / "README.md"
        if root_readme.exists():
            shutil.copy2(root_readme, DOCS_DIR / "README.md")

        root_readme_i18n = PROJECT_ROOT / "README.i18n"
        if root_readme_i18n.is_dir():
            shutil.copytree(root_readme_i18n, DOCS_DIR / "README.i18n", dirs_exist_ok=True)

        root_docs_dir = PROJECT_ROOT / "docs"
        if root_docs_dir.is_dir() and root_docs_dir != DOCS_DIR:
            shutil.copytree(root_docs_dir, DOCS_DIR / "docs", dirs_exist_ok=True)

        exclude_dirs = {'.venv', '_build', '__pycache__', '.git', '_templates', '_static'}
        valid_exts = {'.rst', '.md'}
        doc_entries = []

        for root, dirs, files in os.walk(DOCS_DIR):
            dirs[:] = [d for d in dirs if d not in exclude_dirs and not d.startswith('.')]
            rel_root = Path(root).relative_to(DOCS_DIR)
            for file_name in files:
                if file_name in EXCLUDE_FILES or file_name.startswith('.'):
                    continue
                if Path(file_name).suffix.lower() in valid_exts:
                    rel_path = file_name if rel_root == Path('.') else str(rel_root / file_name)
                    doc_entries.append(Path(rel_path).with_suffix('').as_posix())


        priority = ["README", "goal", "workflow", "workflow_windows11", "BuildStatus_Page", "utility_scripts"]
        doc_entries = sorted(set(doc_entries), key=lambda x: (0, priority.index(x)) if x in priority else (1, 0,
                                                                                                           x.lower()) if "/" not in x else (
            2, 0, x.lower()))
        # Fast test mode: only build 3 pages for fast CI testing
        test_mode = os.environ.get("FAST_DOCS_BUILD", "1") == "1"
        if test_mode:
            doc_entries = [e for e in doc_entries if e in {"README", "README.i18n/README-delang", "goal"}][:3]



        logging.info(f"Found {len(doc_entries)} doc files to include in the index.")
        with open(OUTPUT_FILEPATH, "w", encoding="utf-8") as f:
            f.write("Documentation\n")
            f.write("=============\n\n")
            f.write("This index was automatically generated. Do not edit this file directly.\n\n")
            f.write(".. toctree::\n")
            f.write("   :maxdepth: 2\n\n")
            for entry in doc_entries:
                f.write(f"   {entry}\n")
        logging.info(f"Successfully generated '{OUTPUT_FILEPATH}'.")

    except Exception as e:
        logging.error(f"An error occurred while generating the docs index: {e}")

if __name__ == "__main__":
    generate_docs_index()
