# file config/languagetool_server/maps/en-US/PUNCTUATION_MAP.py
PUNCTUATION_MAP = {
    'period': '.',
    'full stop': '.',
    'torch': '.',
    'dot': '.',
    'point': '.',
    'comma': ',',
    'question mark': '?',
    'christian monk': '?',
    'Christian luck': '?',
    'christian mk': '?',
    'question mk': '?',
    'exclamation mark': '!',
    'exclamation point': '!',
    'colon': ':',
    'semicolon': ';',
    'parenthesis': '(',
    'parentheses': ('(', ')'),
    'open parenthesis': '(',
    'close parenthesis': ')',
    'bracket': '[',
    'open bracket': '[',
    'close bracket': ']',
    'brace': '{',
    'open brace': '{',
    'close brace': '}',
    'hyphen': '-',
    'dash': '-',
    'minus': '-',
    'apostrophe': "'",
    'quote': '"',
    'quotation mark': '"',
    'single quote': "'",
    'double quote': '"',
    'slash': '/',
    'backslash': '\\',
    'underscore': '_',
    'ellipsis': '...',
    'dot dot dot': '...',
    'hash': '#',
    'number sign': '#',
    'and sign': '&',
    'ampersand': '&',
    'at sign': '@',
    'star': '*',


}
