# file config/languagetool_server/PUNCTUATION_MAP.py
PUNCTUATION_MAP = {
    'period': '.',
    'full stop': '.',
    'dot': '.',
    'point': '.',
    'comma': ',',
    'question mark': '?',
    'question MK': '?',
    'exclamation mark': '!',
    'exclamation point': '!',
    'colon': ':',
    'semicolon': ';',
    'parenthesis': '(',
    'parentheses': ('(', ')'),
    'open parenthesis': '(',
    'close parenthesis': ')',
    'bracket': '[',
    'open bracket': '[',
    'close bracket': ']',
    'brace': '{',
    'open brace': '{',
    'close brace': '}',
    'hyphen': '-',
    'dash': '-',
    'minus': '-',
    'apostrophe': "'",
    'quote': '"',
    'quotation mark': '"',
    'single quote': "'",
    'double quote': '"',
    'slash': '/',
    'backslash': '\\',
    'underscore': '_',
    'ellipsis': '...',
    'dot dot dot': '...',
    'hash': '#',
    'number sign': '#',
    'and sign': '&',
    'ampersand': '&',
    'at sign': '@',
    'star': '*',
    'from get up': 'from GitHub',
    'get up': 'GitHub',
    'keep it up': 'GitHub',
    'good job': 'GitHub',
    'q-tip': 'GitHub',
    'kit': 'Git',

    'good status': 'git status',
    'your debt dutch': 'git add .',
    'it\'d push': 'git push',
    'good play': 'git pull',

    'it\'s status': 'git status',
    'the commit': 'git commit',
    'get push': 'git push',
    'push': 'git push',

    'the good status': 'git status',
    'it\'s status': 'git status',
    'good stages': 'git status',

    'Good stages': 'git status',
    'Good status': 'git status',



    'get push': 'git push',
    'good point': 'git pull',
    'get point': 'git pull',
    'good pool': 'git pull',

    'good chat': 'git add .',
    'due to its': 'git add .',

    'Good touch': 'git add .',
    'Get did': 'git add .',

    'gg pool': 'git pull',
    'get the flu': 'git pull',


}
