# CODE_LANGUAGE_DIRECTIVE: ENGLISH_ONLY
# .github/workflows/ci-win-BAT_1update_2start.yml
name: CI Win BAT 1 Update 2 Start

on:
  workflow_dispatch:

jobs:
  test-windows-batch-scripts:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache external tools and models
        id: assets-cache # Give the step an ID to reference it
        uses: actions/cache@v4
        with:
          path: |
            ./LanguageTool-6.6
            ./models/
          key: ${{ runner.os }}-models-tools-${{ hashFiles('tools/download_all_packages.py') }}
          restore-keys: |
            ${{ runner.os }}-models-tools-

      - name: Run setup.bat
        if: steps.assets-cache.outputs.cache-hit != 'true'
        run: |
          powershell -Command "Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force; .\setup\windows11_setup.ps1"      

      - name: Run update.bat
        run: cmd.exe /c "call update.bat"
      
      - name: Start server and verify process
        run: |
          echo "Starting the dictation service in the background..."
          cmd.exe /c "call start_dictation_v2.0.bat"
          
          echo "Waiting for the service to initialize..."
          timeout /t 15
          
          echo "Checking for running python processes..."
          tasklist | findstr /I "python.exe"

      - name: Package Assets as Artifact(90days available from last run of this workflow)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sl5-assets-pack
          path: |
            ./LanguageTool-6.6
            ./models/
