name: Deploy Documentation

on:
  push:
    branches:
      - master  # Oder 'main', je nachdem, wie dein Hauptbranch heißt
  workflow_dispatch: # Ermöglicht manuelles Starten

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements-docs.txt

      - name: Build documentation
        run: make html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build/html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
