name: Deploy Documentation

on:
  release:
    types: [published] 

  push:
    paths:
      - '.github/workflows/deploy-docs'
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build documentation
        run: |
          echo "BRANCH: ${{ github.ref_name }}"
          cd doc_sources
          python -m sphinx -b html . _build/html

      - name: Verify furo installation
        run: |
          echo "BRANCH: ${{ github.ref_name }}"
          python -c "import furo; print(furo.__file__)"
          python -m pip list | grep -i furo

      - name: Install dependencies
        run: |
          echo "BRANCH: ${{ github.ref_name }}"
          python -m pip install sphinx furo myst-parser sphinx-copybutton

      - name: Get latest release version
        run: |
          echo "BRANCH: ${{ github.ref_name }}"
          echo "DOCS_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Build documentation
        run: |
          echo "BRANCH: ${{ github.ref_name }}"
          cd doc_sources
          python -m sphinx -b html . _build/html
#          make -C doc_sources html
      - name: Upload artifact

        uses: actions/upload-pages-artifact@v3
        with:
          path: doc_sources/_build/html
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
