name: Run macos_setup.sh
on:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - name: Run macos_setup.sh
        run: bash ./setup/setup/macos_setup.sh
