# File: .github/workflows/transcription_tool_test.yml

name: 'Test: Transcription Tool'

on:
  workflow_dispatch:
  push:
    paths:
      - 'tools/transcribe_wavefile.py'
      - 'tools/input-test.wav'
      - '.github/workflows/transcription_tool_test.yml'

jobs:
  test-transcription-tool:
    runs-on: ubuntu-latest

    steps:
      - name: '1. Checkout Repository'
        uses: actions/checkout@v4

      - name: '2. Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: '3. Install Python Dependencies'
        run: pip install -r requirements.txt

      - name: '4. Install System Dependencies (ffmpeg)'
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: '5. Download and Unzip Vosk Model'
        run: |
          echo "INFO: Downloading German Vosk model..."
          wget -q https://alphacephei.com/vosk/models/vosk-model-de-0.21.zip
          unzip -q vosk-model-de-0.21.zip
          echo "INFO: Model is ready."

      - name: '6. Run Transcription and Verify Output'
        run: |
          echo "INFO: Running transcription test..."
          python tools/transcribe_wavefile.py tools/input-test.wav | grep "zum nächsten"
