# File: .github/workflows/transcription_tool_test.yml
# This workflow tests the transcription tool by running it on a sample audio file
# and verifying that the output contains an expected German phrase with an umlaut.

name: 'Test: Transcription Tool'

on:
  # Allow manual runs from the Actions tab
  workflow_dispatch:
  # Run on pushes that change the tool or its test components
  push:
    paths:
      - 'tools/transcribe_wavefile.py'
      - 'tools/input-test.wav'
      - '.github/workflows/transcription_tool_test.yml'

jobs:
  test-transcription-tool:
    runs-on: ubuntu-latest

    steps:
      - name: '1. Checkout Repository'
        uses: actions/checkout@v4

      - name: '2. Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: '3. Install Dependencies'
        run: pip install -r requirements.txt

      - name: '4. Download and Unzip Vosk Model'
        run: |
          echo "INFO: Downloading German Vosk model (vosk-model-de-0.21)..."
          wget -q https://github.com/sl5net/Vosk-System-Listener/releases/download/v0.2.0.1/vosk-model-de-0.21.zip
          unzip -q vosk-model-de-0.21.zip
          echo "INFO: Model is ready in the root directory."

      - name: '5. Run Transcription and Verify Output'
        run: |
          echo "INFO: Running transcription test..."
          # Execute the script and pipe its output to grep.
          # The step will fail if 'grep' does not find the expected string.
          python tools/transcribe_wavefile.py tools/input-test.wav | grep "zum nächsten"
