# File: .github/workflows/transcription_tool_test.yml

name: 'Test: Transcription Tool'

on:
  workflow_dispatch:
  push:
    paths:
      - 'tools/transcribe_wavefile.py'
      - 'tools/input-test.wav'

jobs:
  test-transcription-tool:
    runs-on: ubuntu-latest

    steps:
      - name: '1. Checkout Repository'
        uses: actions/checkout@v4

      - name: '2. Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: '3. Install Dependencies'
        run: pip install -r requirements.txt

      - name: '4. Cache Vosk Model'
        id: cache-vosk-model
        uses: actions/cache@v4
        with:
          path: vosk-model-de-0.21
          key: ${{ runner.os }}-vosk-model-de-0.21-v1

      - name: '5. Install System & Model Dependencies'
        # Run this step only if the cache was not restored
        if: steps.cache-vosk-model.outputs.cache-hit != 'true'
        run: |
          echo "INFO: Installing ffmpeg..."
          sudo apt-get update && sudo apt-get install -y ffmpeg
          echo "INFO: Downloading German Vosk model..."
          wget -q https://github.com/sl5net/Vosk-System-Listener/releases/download/v0.2.0.1/vosk-model-de-0.21.zip
          unzip -q vosk-model-de-0.21.zip
          echo "INFO: Dependencies ready."

      - name: '6. Run Transcription and Verify Output'
        run: |
          echo "INFO: Running transcription test with explicit model path..."
          # Pass the model name explicitly to avoid path issues in the script
          python tools/transcribe_wavefile.py tools/input-test.wav --vosk_model vosk-model-de-0.21 | grep "zum nächsten"
