# File: .github/workflows/transcription_tool_test.yml

name: 'Test: Transcription Tool'

on:
  workflow_dispatch:
  push:
    paths:
      - 'tools/transcribe_wavefile.py'
      - 'tools/input-test.wav'

jobs:
  test-transcription-tool:
    runs-on: ubuntu-latest

    steps:
      - name: '1. Checkout Repository'
        uses: actions/checkout@v4

      - name: '2. Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: '3. Install Python Dependencies'
        run: pip install -r requirements.txt

      - name: '4. Install System Dependencies'
        # This step runs every time to ensure tools are present
        run: sudo apt-get update && sudo apt-get install -y ffmpeg libnotify-bin xclip xvfb

      - name: '5. Cache Vosk Model'
        id: cache-vosk-model
        uses: actions/cache@v4
        with:
          # Correct path for the cache
          path: models
          key: ${{ runner.os }}-vosk-model-de-v2

      - name: '6. Download and Unzip Model'
        # This step is skipped if the cache was restored
        if: steps.cache-vosk-model.outputs.cache-hit != 'true'
        run: |
          wget -q https://github.com/sl5net/SL5-aura-service/releases/download/v0.2.0.1/vosk-model-de-0.21.zip
          mkdir models
          unzip -q vosk-model-de-0.21.zip -d models

      - name: '7. Run Transcription and Verify Output'
        run: |
          echo "INFO: Running transcription test..."
          xvfb-run python tools/transcribe_wavefile.py tools/input-test.wav --vosk_model ../models/vosk-model-de-0.21 | grep "zum nächsten"
