name: CI for ubuntu Setup and Test Recording Trigger
on:
  workflow_dispatch:
jobs:
  # Renamed job for clarity
  validate-ubuntu-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run ubuntu_setup.sh
        run: bash ./setup/ubuntu_setup.sh
        
        
      - name: Test Recording Trigger
        run: |
          echo "--> Starting service in background..."
          # Start the main service script and run it in the background
          bash ./scripts/restart_venv_and_run-server.sh &

          echo "--> Waiting 40s for service and models to initialize..."
          # Wait is necessary for LanguageTool server and Vosk models to load
          sleep 40

          echo "--> Triggering a test recording..."
          touch /tmp/vosk_trigger

          echo "--> Waiting 5s for the trigger to be processed and logged..."
          sleep 5

          echo "--> Verifying log file for success indicators..."
          LOG_FILE="log/dictation_service.log"
          if grep "TRIGGER DETECTED!" "$LOG_FILE" && \
             grep "Using model for lang" "$LOG_FILE" && \
             grep "silence_timout now set to" "$LOG_FILE"; then
            echo "✅ Success: All expected log entries for a trigger were found."
          else
            echo "❌ Error: Could not find all expected log entries."
            echo "--- Displaying log content for debugging ---"
            cat "$LOG_FILE"
            exit 1
          fi

          echo "--> Cleaning up background processes..."
          pkill -f dictation_service.py
